# Generated by Django 4.2.6 on 2023-10-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='CustomUser',
            new_name='user',
        ),
    ]
