# Generated by Django 4.2.6 on 2023-10-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_customuser_recipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ainekset',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='ateria',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='instructions',
            new_name='ohjeet',
        ),
    ]
